FROM centos:7

RUN yum install -y openssh openssh-server openssh-clients \
 && ssh-keygen -A \
 && ssh-keygen -t rsa -f /root/.ssh/id_rsa -P '' \
 && cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys \
 && { \
		 echo 'Host *'; \
		 echo '  UserKnownHostsFile /dev/null'; \
		 echo '  StrictHostKeyChecking no'; \
		 echo '  LogLevel quiet'; \
	  } > /root/.ssh/config \

 && sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
 && echo -e '#!/bin/sh\n'\
'echo "root:${ROOT_PASSWORD}" | chpasswd '\
'exec /usr/sbin/sshd -D '\
'\n'\
>/usr/local/bin/entrypoint.sh \
 && chmod -v +x /usr/local/bin/entrypoint.sh \
 

ENTRYPOINT ["entrypoint.sh"]

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

RUN yum -y install openssh openssh-clients openssh-server
EXPOSE 22
RUN ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa
RUN ssh-keygen -f /etc/ssh/ssh_host_ecdsa_key -N '' -t ecdsa
RUN echo "root:jump" | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
CMD ["/usr/sbin/sshd", "-D"]


	  

RUN yum install openssh -y \
 && URL="https://codeload.github.com/apache/hbase/zip/branch-$HBASE_BRANCH" \

 && apk --update add --no-cache maven wget openssh bash openjdk8 \
 &&	wget -t 10 --max-redirect 1 --retry-connrefused -O "/root/hbase-branch-$HBASE_BRANCH.zip" "$URL" \ 
 && apk del wget \
 
 && sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd \
 && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
 && ssh-keygen -A \
 && ssh-keygen -t rsa -f /root/.ssh/id_rsa -P '' \
 && echo "root:${ROOT_PASSWORD}" | chpasswd \





 && unzip -x -q /root/hbase-branch-$HBASE_BRANCH.zip / && cd hbase-branch-$HBASE_BRANCH && mvn -DskipTests package assembly:single && cd ../ \
 && cp /hbase-branch-$HBASE_BRANCH/hbase-assembly/target/*-bin.tar.gz /root/ \
 && cd /root/ && tar -zcf m2.tar.gz .m2/ \
 && apk del maven && rm -rf /usr/share/java/maven-* /root/.m2 /root/.wget* /root/hbase-branch-$HBASE_BRANCH \
 
 && echo -e '#!/bin/sh\n'\
'exec /usr/sbin/sshd -D '\
'\n'\
>/usr/local/bin/entrypoint.sh \
 && chmod -v +x /usr/local/bin/entrypoint.sh \
 
 && rm -rf /var/cache/apk/* /tmp/*
 
